language: python
sudo: false

addons:
  apt:
    packages:
      - pandoc  # contains jq

env:
  - LUA="lua 5.3"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  - luarocks install luacov-coveralls

install:
  - make setup-dev
  - TRAVIS="" make fetch-libs

script:
  - make lint tests
  - (./check-travis-release.sh && make release) || echo "not on release branch"

after_success:
  - luacov-coveralls --root ./ --include 'src/*'
